# Generated by Django 3.1.7 on 2021-02-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Employees',
                'managed': False,
            },
        ),
    ]
